### ISSUE TITLE
Update examples for the to use absolute paths

### ISSUE THREAD

**Issue by gammamatrix** [OakLabsInc/oak#53]
Example:
```
  "scripts": {
    "start": "./node_modules/.bin/oak file:///$PWD/src/index.html",
    "rebuild": "./node_modules/.bin/oak-rebuild .",
    "test": "exit 0;"
  }
```

**Comment by fooius** [comment]
we may want to change the path to `oak` and `oak-rebuild` to use $PWD: 

  "scripts": {
    "start": "$PWD/node_modules/.bin/oak https://seattle-lobby.firebaseapp.com/",
    "rebuild": "$PWD/node_modules/.bin/oak-rebuild .",
    "test": "exit 0;"
  }

**Comment by nucleardreamer** [comment]
None of the examples have a `file://` reference in them, but better error messages have been added  (5d3ef7a731e57345e31c2bc89a43f05aade81681)
