### ISSUE TITLE
Bump chromium/electron version?

### ISSUE THREAD

**Issue by leighkendell** [OakLabsInc/oak#83]
The version of Chromium this package uses is quite old now (66.0.3359.181), is it possible to bump to a more modern version? I'm specifically interested in using the CSS property "backdrop-filter" which was introduced in Chrome 76: https://caniuse.com/#feat=css-backdrop-filter

**Comment by rjoffray** [comment]
You can use the newest base layer of oaklabs/oak:6.0.1 but know that it has not been extensively tested so use at your own risk

**Comment by leighkendell** [comment]
Great, cheers for that!
