### ISSUE TITLE
Docker noWorky ! :)

### ISSUE THREAD

**Issue by supertick** [OakLabsInc/oak#85]
Ahoy OakLabsInc !
I wanted to try using your a oak-lite with docker ... I tried, (cloning this repo, following docker compose run .. etc)
This is the output I get:

```:~/github/oak$ docker-compose up
Creating oak ... done
Attaching to oak
oak    | Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
oak    | error: unknown option `--no-sandbox'
oak exited with code 0
```
Any direction would be appreciated,
Cheers !

**Comment by supertick** [comment]
oh .. this would be the "latest" image

**Comment by rjoffray** [comment]
@supertick what version of node do you have installed and what exactly are the step to repro this error?

**Comment by supertick** [comment]
Sorry, my mistake ... working now - thank you
